describe('Cadastro de usuário', () => {

  it('cadastro com sucesso', () => {
    cy.visit('https://practicesoftwaretesting.com/')
    cy.wait(1000)
    cy.xpath('//*[@id="navbarSupportedContent"]/ul/li[4]/a').click()
    cy.wait(1000)
    cy.xpath('/html/body/app-root/div[2]/app-login/div/div/div/div[3]/p/a[1]').click()
    cy.wait(1000)
    cy.xpath('//*[@id="first_name"]').type('joao')
    cy.xpath('//*[@id="last_name"]').type('souza')
    cy.xpath('/html/body/app-root/div[2]/app-register/div/div/div/form/div/div[3]').type('1991-04-26')
    cy.xpath('//*[@id="country"]').select('Brazil')
    cy.xpath('//*[@id="postal_code"]').type('4444-000')
    cy.xpath('//*[@id="house_number"]').type('123')
    cy.xpath('//*[@id="street"]').type('Rua teste')
    cy.xpath('//*[@id="city"]').type('teste')
    cy.xpath('//*[@id="state"]').type('teste')
    cy.xpath('//*[@id="phone"]').type('987654321')
    cy.xpath('//*[@id="email"]').type('teste123@teste.com')
    cy.xpath('//*[@id="password"]').clear().type('Teste321@', { delay: 100 })
      })
/*
      it('cadastro sem preencher nome', () => {
    cy.visit('https://practicesoftwaretesting.com/')
    cy.wait(1000)
    cy.xpath('//*[@id="navbarSupportedContent"]/ul/li[4]/a').click()
    cy.wait(1000)
    cy.xpath('/html/body/app-root/div[2]/app-login/div/div/div/div[3]/p/a[1]').click()
    cy.wait(1000)
    cy.xpath('//*[@id="first_name"]').clear()
    cy.xpath('//*[@id="last_name"]').type('souza')
    cy.xpath('/html/body/app-root/div[2]/app-register/div/div/div/form/div/div[3]').type('1991-01-01')
    cy.xpath('//*[@id="country"]').select('Brazil')
    cy.xpath('//*[@id="postal_code"]').type('4444-000')
    cy.xpath('//*[@id="house_number"]').type('123')
    cy.xpath('//*[@id="street"]').type('Rua teste')
    cy.xpath('//*[@id="city"]').type('teste')
    cy.xpath('//*[@id="state"]').type('teste')
    cy.xpath('//*[@id="phone"]').type('987654321')
    cy.xpath('//*[@id="email"]').type('teste123@teste.com')
    cy.xpath('//*[@id="password"]').clear().type('Teste321@', { delay: 100 })
    cy.xpath('/html/body/app-root/div[2]/app-register/div/div/div/form/div/button').click()
    cy.wait(1000)
    cy.xpath('//*[@id="first_name-error"]/div').first()
    .should('be.visible')
    .and('contain', 'First name is required')
    cy.wait(1000)
    cy.screenshot('cadastro-sem-nome')
    
  })

  it('cadastro sem preencher país', () => {
    cy.visit('https://practicesoftwaretesting.com/')
    cy.wait(1000)
    cy.xpath('//*[@id="navbarSupportedContent"]/ul/li[4]/a').click()
    cy.wait(1000)
    cy.xpath('/html/body/app-root/div[2]/app-login/div/div/div/div[3]/p/a[1]').click()
    cy.wait(1000)
    cy.xpath('//*[@id="first_name"]').type('joao')
    cy.xpath('//*[@id="last_name"]').type('souza')
    cy.xpath('/html/body/app-root/div[2]/app-register/div/div/div/form/div/div[3]').type('1991-01-01')
    cy.xpath('//*[@id="postal_code"]').type('4444-000')
    cy.xpath('//*[@id="house_number"]').type('123')
    cy.xpath('//*[@id="street"]').type('Rua teste')
    cy.xpath('//*[@id="city"]').type('teste')
    cy.xpath('//*[@id="state"]').type('teste')
    cy.xpath('//*[@id="phone"]').type('987654321')
    cy.xpath('//*[@id="email"]').type('teste123@teste.com')
    cy.xpath('//*[@id="password"]').clear().type('Teste321@', { delay: 100 })
    cy.xpath('/html/body/app-root/div[2]/app-register/div/div/div/form/div/button').click()
    cy.wait(1000)
    cy.xpath('//*[@id="country-error"]/div').first()
    .should('be.visible')
    .and('contain', 'Country is required')
    cy.wait(1000)
    cy.screenshot('cadastro-sem-pais')  
    })
   */
})



